language: php

php:
- '5.4'
- '5.3'

install:
    - composer install

before_script: phpenv config-add native5.ini  

script : phpunit -vvv --configuration phpunit.xml

branches:
    only:
        - development
